apiVersion: 1

datasources: 
  - name: Tempo
    type: tempo
    uid: tempo_uid_1
    access: proxy
    url: http://host.docker.internal:6778
    jsonData:
      tracesToLogsV2:
        customQuery: true
        datasourceUid: loki_uid_1
        query: '{trace_id="$${__span.traceId}", span_id="$${__span.spanId}"}'
        spanEndTimeShift: 5m
        spanStartTimeShift: -5m